still messing with postgresql

diff --git a/rangerrick/common/crypto/finkinfo/postgresql80-ssl.patch b/rangerrick/common/crypto/finkinfo/postgresql80-ssl.patch
--- a/rangerrick/common/crypto/finkinfo/postgresql80-ssl.patch
+++ b/rangerrick/common/crypto/finkinfo/postgresql80-ssl.patch
@@ -1,6 +1,6 @@
-diff -uNr postgresql-8.0.1/contrib/Makefile postgresql-8.0.1-new/contrib/Makefile
---- postgresql-8.0.1/contrib/Makefile	Tue Dec 14 17:50:23 2004
-+++ postgresql-8.0.1-new/contrib/Makefile	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/contrib/Makefile postgresql-8.0.2-new/contrib/Makefile
+--- postgresql-8.0.2/contrib/Makefile	Tue Dec 14 17:50:23 2004
++++ postgresql-8.0.2-new/contrib/Makefile	Mon Apr 11 19:37:59 2005
 @@ -37,7 +37,6 @@
  		string		\
  		tablefunc	\
@@ -9,19 +9,55 @@ diff -uNr postgresql-8.0.1/contrib/Makefile postgresql-8.0.1-new/contrib/Makefil
  		tsearch2	\
  		userlock	\
  		vacuumlo
-diff -uNr postgresql-8.0.1/pgsql.sh postgresql-8.0.1-new/pgsql.sh
---- postgresql-8.0.1/pgsql.sh	Wed Dec 31 19:00:00 1969
-+++ postgresql-8.0.1-new/pgsql.sh	Sat Apr  9 17:35:12 2005
-@@ -0,0 +1,21 @@
+diff -uNr postgresql-8.0.2/pgsql.sh postgresql-8.0.2-new/pgsql.sh
+--- postgresql-8.0.2/pgsql.sh	Wed Dec 31 19:00:00 1969
++++ postgresql-8.0.2-new/pgsql.sh	Mon Apr 11 19:43:10 2005
+@@ -0,0 +1,57 @@
 +#!/bin/sh
-+
-+for flag in "-n" "-d" "-s" "-u" "-v"; do
-+	ulimit $flag 65536 >/dev/null 2>&1 || :
-+done
 +
 +PREFIX="@INSTPREFIX@"
 +DATADIR="${PREFIX}/var/postgresql-8.0/data"
 +LOGFILE="${PREFIX}/var/postgresql-8.0/pgsql.log"
++
++export LANG=C
++unset LC_ALL
++
++SHMMAX=`sysctl kern.sysv.shmmax | cut -d' ' -f2-`
++SHMMNI=`sysctl kern.sysv.shmmni | cut -d' ' -f2-`
++SHMALL=`sysctl kern.sysv.shmall | cut -d' ' -f2-`
++
++if [ "$SHMMAX" -lt "8388608" ] || [ "$SHMMNI" -lt "64" ] || [ "$SHMALL" -lt "32768" ]; then
++	echo "ERROR: You must set your shared memory resources higher for PostgreSQL to function."
++	if [ -f /etc/rc.local_tuning ]; then
++		echo "       You already have an /etc/rc.local_tuning so I'm assuming you know what you're"
++		echo "       doing.  Please update your shared memory settings to something higher and"
++		echo "       give it another shot."
++	else
++		echo "       I am creating a default configuration in /etc/rc.local_tuning that should let"
++		echo "       you start PostgreSQL, but it's probably best if you tune it yourself when"
++		echo "       I'm done.  You will have to reboot before it will take effect."
++		cat <<END >/etc/rc.local_tuning
++sysctl -w kern.sysv.shmmax=8388608
++sysctl -w kern.sysv.shmmin=1
++sysctl -w kern.sysv.shmmni=64
++sysctl -w kern.sysv.shmseg=8
++sysctl -w kern.sysv.shmall=32768
++END
++	fi
++fi
++
++if [ -d "$DATADIR" ]; then
++	chown -R postgres "$DATADIR"
++else
++	echo -e "- making postgresql directories: \c"
++	mkdir -p "$DATADIR"
++	chown -R postgres "$DATADIR"
++	echo "ok"
++
++	echo -e "- initializing database in $DATADIR: \c"
++	sudo -u postgres %p/bin/initdb-8.0 -D "$DATADIR" >/tmp/pgsql-init-8.0.log 2>&1 || die "couldn't initialize database"
++	echo "ok"
++fi
 +
 +case "$1" in
 +	start)
@@ -34,9 +70,9 @@ diff -uNr postgresql-8.0.1/pgsql.sh postgresql-8.0.1-new/pgsql.sh
 +		unset LC_ALL; LANG=C sudo -u postgres "${PREFIX}/bin/pg_ctl-8.0" stop -D "$DATADIR" -m fast
 +		;;
 +esac
-diff -uNr postgresql-8.0.1/src/Makefile.global.in postgresql-8.0.1-new/src/Makefile.global.in
---- postgresql-8.0.1/src/Makefile.global.in	Wed Jan 26 14:24:15 2005
-+++ postgresql-8.0.1-new/src/Makefile.global.in	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/Makefile.global.in postgresql-8.0.2-new/src/Makefile.global.in
+--- postgresql-8.0.2/src/Makefile.global.in	Fri Mar 25 13:18:39 2005
++++ postgresql-8.0.2-new/src/Makefile.global.in	Mon Apr 11 19:37:59 2005
 @@ -65,21 +65,21 @@
  libexecdir := @libexecdir@
  ifeq "$(findstring pgsql, $(libexecdir))" ""
@@ -89,9 +125,9 @@ diff -uNr postgresql-8.0.1/src/Makefile.global.in postgresql-8.0.1-new/src/Makef
  endif
  endif
  endif
-diff -uNr postgresql-8.0.1/src/Makefile.shlib postgresql-8.0.1-new/src/Makefile.shlib
---- postgresql-8.0.1/src/Makefile.shlib	Sat Nov 20 16:13:04 2004
-+++ postgresql-8.0.1-new/src/Makefile.shlib	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/Makefile.shlib postgresql-8.0.2-new/src/Makefile.shlib
+--- postgresql-8.0.2/src/Makefile.shlib	Sat Nov 20 16:13:04 2004
++++ postgresql-8.0.2-new/src/Makefile.shlib	Mon Apr 11 19:37:59 2005
 @@ -101,11 +101,11 @@
    ifeq ($(DLTYPE), library)
      # linkable library
@@ -106,9 +142,9 @@ diff -uNr postgresql-8.0.1/src/Makefile.shlib postgresql-8.0.1-new/src/Makefile.
    endif
    shlib			= lib$(NAME).$(SO_MAJOR_VERSION).$(SO_MINOR_VERSION)$(DLSUFFIX)
    shlib_major		= lib$(NAME).$(SO_MAJOR_VERSION)$(DLSUFFIX)
-diff -uNr postgresql-8.0.1/src/backend/main/main.c postgresql-8.0.1-new/src/backend/main/main.c
---- postgresql-8.0.1/src/backend/main/main.c	Fri Dec 31 16:59:53 2004
-+++ postgresql-8.0.1-new/src/backend/main/main.c	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/backend/main/main.c postgresql-8.0.2-new/src/backend/main/main.c
+--- postgresql-8.0.2/src/backend/main/main.c	Fri Dec 31 16:59:53 2004
++++ postgresql-8.0.2-new/src/backend/main/main.c	Mon Apr 11 19:37:59 2005
 @@ -56,6 +56,7 @@
  	struct passwd *pw;
  #endif
@@ -145,9 +181,9 @@ diff -uNr postgresql-8.0.1/src/backend/main/main.c postgresql-8.0.1-new/src/back
  #ifdef WIN32
  	  || (len >= 14 && strcmp(argv[0] + len - 14, "postmaster.exe") == 0)
  #endif
-diff -uNr postgresql-8.0.1/src/backend/utils/fmgr/dfmgr.c postgresql-8.0.1-new/src/backend/utils/fmgr/dfmgr.c
---- postgresql-8.0.1/src/backend/utils/fmgr/dfmgr.c	Fri Dec 31 17:01:31 2004
-+++ postgresql-8.0.1-new/src/backend/utils/fmgr/dfmgr.c	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/backend/utils/fmgr/dfmgr.c postgresql-8.0.2-new/src/backend/utils/fmgr/dfmgr.c
+--- postgresql-8.0.2/src/backend/utils/fmgr/dfmgr.c	Fri Dec 31 17:01:31 2004
++++ postgresql-8.0.2-new/src/backend/utils/fmgr/dfmgr.c	Mon Apr 11 19:37:59 2005
 @@ -305,6 +305,26 @@
  		pfree(full);
  	}
@@ -175,9 +211,9 @@ diff -uNr postgresql-8.0.1/src/backend/utils/fmgr/dfmgr.c postgresql-8.0.1-new/s
  	new = palloc(strlen(name) + strlen(DLSUFFIX) + 1);
  	strcpy(new, name);
  	strcat(new, DLSUFFIX);
-diff -uNr postgresql-8.0.1/src/backend/utils/misc/postgresql.conf.sample postgresql-8.0.1-new/src/backend/utils/misc/postgresql.conf.sample
---- postgresql-8.0.1/src/backend/utils/misc/postgresql.conf.sample	Fri Nov  5 14:16:16 2004
-+++ postgresql-8.0.1-new/src/backend/utils/misc/postgresql.conf.sample	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/backend/utils/misc/postgresql.conf.sample postgresql-8.0.2-new/src/backend/utils/misc/postgresql.conf.sample
+--- postgresql-8.0.2/src/backend/utils/misc/postgresql.conf.sample	Wed Mar 23 23:36:59 2005
++++ postgresql-8.0.2-new/src/backend/utils/misc/postgresql.conf.sample	Mon Apr 11 19:37:59 2005
 @@ -61,7 +61,7 @@
  # - Security & Authentication -
  
@@ -187,9 +223,93 @@ diff -uNr postgresql-8.0.1/src/backend/utils/misc/postgresql.conf.sample postgre
  #password_encryption = true
  #krb_server_keyfile = ''
  #db_user_namespace = false
-diff -uNr postgresql-8.0.1/src/interfaces/ecpg/compatlib/Makefile postgresql-8.0.1-new/src/interfaces/ecpg/compatlib/Makefile
---- postgresql-8.0.1/src/interfaces/ecpg/compatlib/Makefile	Mon Jul 12 20:06:39 2004
-+++ postgresql-8.0.1-new/src/interfaces/ecpg/compatlib/Makefile	Sun Apr 10 00:20:15 2005
+diff -uNr postgresql-8.0.2/src/bin/initdb/initdb.c postgresql-8.0.2-new/src/bin/initdb/initdb.c
+--- postgresql-8.0.2/src/bin/initdb/initdb.c	Thu Jan 27 19:36:17 2005
++++ postgresql-8.0.2-new/src/bin/initdb/initdb.c	Mon Apr 11 19:37:59 2005
+@@ -118,7 +118,7 @@
+ 
+ /* defaults */
+ int			n_connections = 10;
+-int			n_buffers = 50;
++int			n_buffers = 20;
+ 
+ /*
+  * Warning messages for authentication methods
+@@ -2313,7 +2313,7 @@
+ 	sprintf(pgdenv, "PGDATA=%s", pg_data);
+ 	putenv(pgdenv);
+ 
+-	if ((ret = find_other_exec(argv[0], "postgres", PG_VERSIONSTR,
++	if ((ret = find_other_exec(argv[0], "postgres-8.0", PG_VERSIONSTR,
+ 							   backend_exec)) < 0)
+ 	{
+ 		char full_path[MAXPGPATH];
+@@ -2323,14 +2323,14 @@
+ 
+ 		if (ret == -1)
+ 			fprintf(stderr,
+-					_("The program \"postgres\" is needed by %s "
++					_("The program \"postgres-8.0\" is needed by %s "
+ 					  "but was not found in the\n"
+ 					  "same directory as \"%s\".\n"
+ 					  "Check your installation.\n"),
+ 					progname, full_path);
+ 		else
+ 			fprintf(stderr,
+-					_("The program \"postgres\" was found by \"%s\"\n"
++					_("The program \"postgres-8.0\" was found by \"%s\"\n"
+ 					  "but was not the same version as %s.\n"
+ 					  "Check your installation.\n"),
+ 					full_path, progname);
+@@ -2617,7 +2617,7 @@
+ 	get_parent_directory(bin_dir);
+ 	
+ 	printf(_("\nSuccess. You can now start the database server using:\n\n"
+-			 "    %s%s%s%spostmaster -D %s%s%s\n"
++			 "    %s%s%s%spostmaster-8.0 -D %s%s%s\n"
+ 			 "or\n"
+ 			 "    %s%s%s%spg_ctl -D %s%s%s -l logfile start\n\n"),
+ 	  QUOTE_PATH, bin_dir, QUOTE_PATH, (strlen(bin_dir) > 0) ? DIR_SEP : "",
+diff -uNr postgresql-8.0.2/src/bin/pg_ctl/pg_ctl.c postgresql-8.0.2-new/src/bin/pg_ctl/pg_ctl.c
+--- postgresql-8.0.2/src/bin/pg_ctl/pg_ctl.c	Fri Dec 31 17:03:05 2004
++++ postgresql-8.0.2-new/src/bin/pg_ctl/pg_ctl.c	Mon Apr 11 19:37:59 2005
+@@ -532,7 +532,7 @@
+ 
+ 		postmaster_path = xmalloc(MAXPGPATH);
+ 
+-		if ((ret = find_other_exec(argv0, "postmaster", PM_VERSIONSTR,
++		if ((ret = find_other_exec(argv0, "postmaster-8.0", PM_VERSIONSTR,
+ 								   postmaster_path)) < 0)
+ 		{
+ 			char full_path[MAXPGPATH];
+@@ -541,13 +541,13 @@
+ 				StrNCpy(full_path, progname, MAXPGPATH);
+ 	
+ 			if (ret == -1)
+-				write_stderr(_("The program \"postmaster\" is needed by %s "
++				write_stderr(_("The program \"postmaster-8.0\" is needed by %s "
+ 							   "but was not found in the\n"
+ 							   "same directory as \"%s\".\n"
+ 							   "Check your installation.\n"),
+ 							 progname, full_path);
+ 			else
+-				write_stderr(_("The program \"postmaster\" was found by \"%s\"\n"
++				write_stderr(_("The program \"postmaster-8.0\" was found by \"%s\"\n"
+ 							   "but was not the same version as %s.\n"
+ 							   "Check your installation.\n"),
+ 							 full_path, progname);
+@@ -839,7 +839,7 @@
+ 	}
+ 	else
+ 	{
+-		ret = find_other_exec(argv0, "postmaster", PM_VERSIONSTR, cmdLine);
++		ret = find_other_exec(argv0, "postmaster-8.0", PM_VERSIONSTR, cmdLine);
+ 		if (ret != 0)
+ 		{
+ 			write_stderr(_("%s: could not find postmaster program executable\n"), progname);
+diff -uNr postgresql-8.0.2/src/interfaces/ecpg/compatlib/Makefile postgresql-8.0.2-new/src/interfaces/ecpg/compatlib/Makefile
+--- postgresql-8.0.2/src/interfaces/ecpg/compatlib/Makefile	Sun Mar 13 17:04:45 2005
++++ postgresql-8.0.2-new/src/interfaces/ecpg/compatlib/Makefile	Mon Apr 11 19:37:59 2005
 @@ -20,6 +20,7 @@
  override CPPFLAGS := -I$(top_srcdir)/src/interfaces/ecpg/include -I$(libpq_srcdir) \
  	-I$(top_srcdir)/src/include/utils $(CPPFLAGS)
@@ -198,9 +318,9 @@ diff -uNr postgresql-8.0.1/src/interfaces/ecpg/compatlib/Makefile postgresql-8.0
  SHLIB_LINK = -L../ecpglib -lecpg -L../pgtypeslib -lpgtypes $(libpq) \
  	$(filter -lintl -lssl -lcrypto -lkrb5 -lcrypt -lm, $(LIBS)) $(PTHREAD_LIBS)
  
-diff -uNr postgresql-8.0.1/src/interfaces/ecpg/ecpglib/Makefile postgresql-8.0.1-new/src/interfaces/ecpg/ecpglib/Makefile
---- postgresql-8.0.1/src/interfaces/ecpg/ecpglib/Makefile	Wed Jan 26 14:24:17 2005
-+++ postgresql-8.0.1-new/src/interfaces/ecpg/ecpglib/Makefile	Sun Apr 10 00:19:39 2005
+diff -uNr postgresql-8.0.2/src/interfaces/ecpg/ecpglib/Makefile postgresql-8.0.2-new/src/interfaces/ecpg/ecpglib/Makefile
+--- postgresql-8.0.2/src/interfaces/ecpg/ecpglib/Makefile	Sun Mar 13 17:04:45 2005
++++ postgresql-8.0.2-new/src/interfaces/ecpg/ecpglib/Makefile	Mon Apr 11 19:37:59 2005
 @@ -19,6 +19,7 @@
  
  override CPPFLAGS := -DFRONTEND -I$(top_srcdir)/src/interfaces/ecpg/include \
@@ -209,9 +329,9 @@ diff -uNr postgresql-8.0.1/src/interfaces/ecpg/ecpglib/Makefile postgresql-8.0.1
  override CFLAGS += $(PTHREAD_CFLAGS)
  
  # Need to recomple any libpgport object files
-diff -uNr postgresql-8.0.1/src/makefiles/Makefile.darwin postgresql-8.0.1-new/src/makefiles/Makefile.darwin
---- postgresql-8.0.1/src/makefiles/Makefile.darwin	Thu Dec 16 22:52:48 2004
-+++ postgresql-8.0.1-new/src/makefiles/Makefile.darwin	Sat Apr  9 17:35:12 2005
+diff -uNr postgresql-8.0.2/src/makefiles/Makefile.darwin postgresql-8.0.2-new/src/makefiles/Makefile.darwin
+--- postgresql-8.0.2/src/makefiles/Makefile.darwin	Thu Dec 16 22:52:48 2004
++++ postgresql-8.0.2-new/src/makefiles/Makefile.darwin	Mon Apr 11 19:37:59 2005
 @@ -13,6 +13,6 @@
  # Rule for building shared libs (currently used only for regression test
  # shlib ... should go away, since this is not really enough knowledge)
