some pending updates

diff --git a/rangerrick/10.3/main/finkinfo/database/libpqxx-2.patch b/rangerrick/10.3/main/finkinfo/database/libpqxx-2.patch
--- a/rangerrick/10.3/main/finkinfo/database/libpqxx-2.patch
+++ b/rangerrick/10.3/main/finkinfo/database/libpqxx-2.patch
@@ -1,7 +1,7 @@
-diff -uNr libpqxx-2.5.2/configure libpqxx-2.5.2-new/configure
---- libpqxx-2.5.2/configure	Tue May 10 07:11:29 2005
-+++ libpqxx-2.5.2-new/configure	Wed May 11 13:52:37 2005
-@@ -20248,7 +20248,8 @@
+diff -uNr libpqxx-2.5.5/configure libpqxx-2.5.5-new/configure
+--- libpqxx-2.5.5/configure	2005-07-01 03:52:28.000000000 -0400
++++ libpqxx-2.5.5-new/configure	2005-07-07 10:15:32.000000000 -0400
+@@ -20330,7 +20330,8 @@
  { echo "$as_me:$LINENO: using PostgreSQL libraries at $with_postgres_lib" >&5
  echo "$as_me: using PostgreSQL libraries at $with_postgres_lib" >&6;}
  
@@ -11,27 +11,18 @@ diff -uNr libpqxx-2.5.2/configure libpqxx-2.5.2-new/configure
  
  POSTGRES_LIB="-L${with_postgres_lib} -R${with_postgres_lib} -lpq"
  
-@@ -21454,7 +21455,7 @@
- _ACEOF
- rm -f conftest.$ac_objext
- if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
--  (eval $ac_compile) 2>conftest.er1
-+  (eval $ac_compile -Werror) 2>conftest.er1
+@@ -21604,7 +21605,7 @@
    ac_status=$?
-   grep -v '^ *+' conftest.er1 >conftest.err
-   rm -f conftest.er1
-@@ -21503,7 +21504,7 @@
- _ACEOF
- rm -f conftest.$ac_objext
- if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
--  (eval $ac_compile) 2>conftest.er1
-+  (eval $ac_compile -Werror) 2>conftest.er1
-   ac_status=$?
-   grep -v '^ *+' conftest.er1 >conftest.err
-   rm -f conftest.er1
-diff -uNr libpqxx-2.5.2/src/Makefile.in libpqxx-2.5.2-new/src/Makefile.in
---- libpqxx-2.5.2/src/Makefile.in	Tue May 10 07:11:26 2005
-+++ libpqxx-2.5.2-new/src/Makefile.in	Wed May 11 13:46:24 2005
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  strerror_r_charp=yes
++  strerror_r_charp=no
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+diff -uNr libpqxx-2.5.5/src/Makefile.in libpqxx-2.5.5-new/src/Makefile.in
+--- libpqxx-2.5.5/src/Makefile.in	2005-07-01 03:52:26.000000000 -0400
++++ libpqxx-2.5.5-new/src/Makefile.in	2005-07-07 10:11:51.000000000 -0400
 @@ -214,9 +214,9 @@
  
  
@@ -40,7 +31,7 @@ diff -uNr libpqxx-2.5.2/src/Makefile.in libpqxx-2.5.2-new/src/Makefile.in
 +#libpqxx_version = -release $(PQXXVERSION)
  # Uncomment to build a versioned library
 -#libpqxx_version = -version-info $(ABI_CURRENT):$(ABI_REVISION):$(ABI_AGE)
-+libpqxx_version = -version-info 7:2:5
++libpqxx_version = -version-info 7:0:5
  libpqxx_la_LDFLAGS = $(libpqxx_version) \
  	-rpath $(libdir) \
  	${POSTGRES_LIB}
