Changes, it runs, add cyrus group/user to passwd package for it

diff --git a/cattrap/cyrus-imapd-2.1.12-1.patch b/cattrap/cyrus-imapd-2.1.12-1.patch
--- a/cattrap/cyrus-imapd-2.1.12-1.patch
+++ b/cattrap/cyrus-imapd-2.1.12-1.patch
@@ -31,51 +31,6 @@
  #   undef SPT_TYPE
 
 
---- cyrus-imapd-2.1.12/configure	Tue Feb  4 08:31:13 2003
-+++ cyrus-imapd-2.1.12-patched/configure	Fri Feb 14 17:08:22 2003
-@@ -1499,7 +1499,7 @@
-     CFLAGS="-Wall ${CFLAGS}"
-   GCC_VERSION=`$CC -v 2>&1 | sed -n -e '/version/s/.*version \([0-9]\)\..*/\1/p'`
-   if test "$GCC_VERSION" != "3"; then
--    CPPFLAGS="${CPPFLAGS} -I/usr/local/include"
-+    CPPFLAGS="${CPPFLAGS}"
-   fi
- else
-   CPPFLAGS="${CPPFLAGS} -I/usr/local/include"
-@@ -1507,7 +1507,7 @@
- 
-   # this is CMU ADD LIBPATH
-   if test "$andrew_runpath_switch" = "none" ; then
--	LDFLAGS="-L"/usr/local/lib" ${LDFLAGS}"
-+	LDFLAGS="${LDFLAGS}"
-   else
- 	LDFLAGS="-L"/usr/local/lib" $andrew_runpath_switch"/usr/local/lib" ${LDFLAGS}"
-   fi
-@@ -5241,7 +5241,7 @@
- EOF
- if { (eval echo configure:5243: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-   rm -rf conftest*
--  eval "ac_cv_lib_$ac_lib_var=yes"
-+  eval "ac_cv_lib_$ac_lib_var=no"
- else
-   echo "configure: failed program was:" >&5
-   cat conftest.$ac_ext >&5
-@@ -5353,12 +5353,11 @@
- 
- 
- 	if test "${with_com_err}" = "no"; then
--	  echo "configure: warning: com_err is required; included version will be used." 1>&2
-+	  echo "configure: included com_err will be used." 1>&2
- 	  with_com_err="yes"
- 	else
- 	  if test "${COMPILE_ET}" = "no compile et" -o "${COMPILE_ET}" = ""; then
--	    echo "configure: warning: Parts of com_err distribuion were found, but not compile_et." 1>&2
--	    echo "configure: warning: Will build com_err from included sources." 1>&2
-+	    echo "configure: included com_err will be used." 1>&2
- 	    with_com_err="yes" # build it ourselves
- 	  fi
- 	fi
-
 --- cyrus-imapd-2.1.12/imap/cvt_cyrusdb.c	Thu Nov  7 07:43:20 2002
 +++ cyrus-imapd-2.1.12-patched/imap/cvt_cyrusdb.c	Fri Feb 14 17:26:18 2003
 @@ -62,7 +62,7 @@
@@ -145,7 +100,7 @@
  # Note that we use the *dynamic* sasl libraries
 -SASL_LIB=@LIB_DYN_SASL@
 -SASL_INC=@DYNSASLFLAGS@
-+SASL_LIB=-L@prefix@/lib
++SASL_LIB=-L@prefix@/lib -lsasl2
 +SASL_INC=-I@prefix@/include
  OPENSSL_LIB=@OPENSSL_LIB@
  OPENSSL_INC=@OPENSSL_INC@
@@ -168,7 +123,7 @@
  # Note that we use the *dynamic* sasl libraries
 -SASL_LIB=@LIB_DYN_SASL@
 -SASL_INC=@DYNSASLFLAGS@
-+SASL_LIB=-L@prefix@/lib
++SASL_LIB=-L@prefix@/lib -lsasl2
 +SASL_INC=-I@prefix@/include
  OPENSSL_LIB=@OPENSSL_LIB@
  OPENSSL_INC=@OPENSSL_INC@
@@ -206,3 +161,124 @@
  #define MAX_FILENAME_LEN 255
  
  static int  evalcheck(char*, int, char*);
+
+--- cyrus-imapd-2.1.12/configure	Tue Feb  4 08:31:13 2003
++++ cyrus-imapd-2.1.12-patched/configure	Wed Feb 19 11:24:21 2003
+@@ -1499,7 +1499,7 @@
+     CFLAGS="-Wall ${CFLAGS}"
+   GCC_VERSION=`$CC -v 2>&1 | sed -n -e '/version/s/.*version \([0-9]\)\..*/\1/p'`
+   if test "$GCC_VERSION" != "3"; then
+-    CPPFLAGS="${CPPFLAGS} -I/usr/local/include"
++    CPPFLAGS="${CPPFLAGS}"
+   fi
+ else
+   CPPFLAGS="${CPPFLAGS} -I/usr/local/include"
+@@ -1507,7 +1507,7 @@
+ 
+   # this is CMU ADD LIBPATH
+   if test "$andrew_runpath_switch" = "none" ; then
+-	LDFLAGS="-L"/usr/local/lib" ${LDFLAGS}"
++	LDFLAGS="${LDFLAGS}"
+   else
+ 	LDFLAGS="-L"/usr/local/lib" $andrew_runpath_switch"/usr/local/lib" ${LDFLAGS}"
+   fi
+@@ -2841,7 +2841,7 @@
+ 	    BDB_LIBADD=""
+ 	fi
+ 
+-        for dbname in db-4.1 db4.1 db-4.0 db4.0 db-4 db4 db-3.3 db3.3 db-3.2 db3.2 db-3.1 db3.1 db-3 db3 db
++        for dbname in db-3.3 db3.3 db-3.2 db3.2 db-3 db3 db
+           do
+             echo $ac_n "checking for db_create in -l$dbname""... $ac_c" 1>&6
+ echo "configure:2848: checking for db_create in -l$dbname" >&5
+@@ -5241,7 +5241,7 @@
+ EOF
+ if { (eval echo configure:5243: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+   rm -rf conftest*
+-  eval "ac_cv_lib_$ac_lib_var=yes"
++  eval "ac_cv_lib_$ac_lib_var=no"
+ else
+   echo "configure: failed program was:" >&5
+   cat conftest.$ac_ext >&5
+@@ -5357,8 +5357,7 @@
+ 	  with_com_err="yes"
+ 	else
+ 	  if test "${COMPILE_ET}" = "no compile et" -o "${COMPILE_ET}" = ""; then
+-	    echo "configure: warning: Parts of com_err distribuion were found, but not compile_et." 1>&2
+-	    echo "configure: warning: Will build com_err from included sources." 1>&2
++            echo "configure: included com_err will be used." 1>&2
+ 	    with_com_err="yes" # build it ourselves
+ 	  fi
+ 	fi
+
+--- cyrus-imapd-2.1.12/master/masterconf.c	Thu Nov  7 07:43:31 2002
++++ cyrus-imapd-2.1.12-patched/master/masterconf.c	Wed Feb 19 12:17:47 2003
+@@ -58,7 +58,7 @@
+ 
+ #include "masterconf.h"
+ 
+-#define CONFIG_FILENAME "/etc/cyrus.conf"
++#define CONFIG_FILENAME "@prefix@/etc/cyrus.conf"
+ 
+ struct configlist {
+     char *key;
+
+--- cyrus-imapd-2.1.12/master/conf/normal.conf	Wed Oct  2 06:46:01 2002
++++ cyrus-imapd-2.1.12-patched/master/conf/normal.conf	Wed Feb 19 12:55:01 2003
+@@ -19,10 +19,10 @@
+ 
+   # at least one LMTP is required for delivery
+ #  lmtp		cmd="lmtpd" listen="lmtp" prefork=0
+-  lmtpunix	cmd="lmtpd" listen="/var/imap/socket/lmtp" prefork=0
++  lmtpunix	cmd="lmtpd" listen="@prefix@/var/imap/socket/lmtp" prefork=0
+ 
+   # this is only necessary if using notifications
+-#  notify	cmd="notifyd" listen="/var/imap/socket/notify" proto="udp" prefork=1
++#  notify	cmd="notifyd" listen="@prefix@/var/imap/socket/notify" proto="udp" prefork=1
+ }
+ 
+ EVENTS {
+
+--- cyrus-imapd-2.1.12/Makefile.in	Tue Feb  4 07:43:52 2003
++++ cyrus-imapd-2.1.12-patched/Makefile.in	Thu Feb 20 12:44:48 2003
+@@ -95,10 +95,10 @@
+ 	$(srcdir)/install-sh -d ${DESTDIR}$(exec_prefix)/bin
+ 	$(srcdir)/install-sh -d ${DESTDIR}$(exec_prefix)/lib
+ 	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/include/cyrus
+-	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/man/man1
+-	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/man/man3
+-	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/man/man5
+-	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/man/man8
++	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/share/man/man1
++	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/share/man/man3
++	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/share/man/man5
++	$(srcdir)/install-sh -d ${DESTDIR}$(prefix)/share/man/man8
+ 	@for d in  $(SUBDIRS); \
+ 	do \
+ 		(cd $$d; echo "### Making" install "in" `pwd`;	\
+
+--- cyrus-imapd-2.1.12/imapd.conf	Wed Feb 19 13:48:19 2003
++++ cyrus-imapd-2.1.12-patched/imapd.conf	Thu Feb 20 15:58:50 2003
+@@ -0,0 +1,22 @@
++# 
++# Sample imap.conf for cyrus-imapd, for more options see 'man imapd.conf'
++#
++configdirectory:	@prefix@/var/imap
++partition-default:	@prefix@/var/spool/imap
++#sievedir:		@prefix@/var/imap/sieve
++
++#tls_cert_file:        @prefix@/etc/server.crt
++#tls_key_file:		@prefix@/etc/server.key
++
++# Don't use an everyday user as admin.
++admins:		cyrus
++
++#hashimapspool:	yes
++#allowanonymouslogin:	no
++#allowplaintext:       no
++
++# Use this if sieve-scripts could be in ~user/.sieve.
++#sieveusehomedir:	yes
++
++# Use saslauthd if you want to use pam for imap.
++#sasl_pwcheck_method:	saslauthd
