Correct _ sort of

diff --git a/jfmertens/main/finkinfo/sci/singular.patch b/jfmertens/main/finkinfo/sci/singular.patch
--- a/jfmertens/main/finkinfo/sci/singular.patch
+++ b/jfmertens/main/finkinfo/sci/singular.patch
@@ -1,15 +1,78 @@
 ## PatchScript put here to escape the dreadfull fink indexing
-# (% expansions can't be used _ to correct when re-including in info file)
 
 ### '--no-same-permissions' doesn't seem to work correctly
 chmod -R a+rX,u+w *
+# and fix immediately remaining perms :
+chmod a-x Singular/LIB/*.lib
+#
+#
+#
+nooptflags="-O0 -ggdb"
+warnflags="-Wall -Wcast-align -W -Wno-unused"
+mflags="-mcpu=`machine|sed 's,ppc,,'` -mtune=`machine|sed 's,ppc,,'`"
+# We can't just put -mdynamic-no-pic in the CXXFLAGS, and let it be overridden by an SFLAG -fPIC when building the .dl_o files,
+# because then g++ complains when building the .dl_o files (opposite behaviour with the -mdynamic-no-pic implied by -fast) :
+# "cc1plus: warning: -mdynamic-no-pic overrides -fpic or -fPIC" _ with ensuing breakdown by ld
+# Thus we'll put below all the CXXFLAGS into the SFLAGS for the .dl_o files,
+# and hence first remove the CXXFLAGS in the .dl_o targets:
+sed -ri.bak '/\.dl_o :/,+1s/ \$\{CXXFLAGS\}//' Singular/Makefile.in
+#
+# flags="-fast -faltivec"
+# works _ but let us be more modest (and a bit better) :
+# (the first series is there just because it wasn't clear they were included in -O3 in Apple's version)
+# -fsched-spec-load gave very bad performance _ maybe removing the others too ? First try -fno-sched-spec_ was worse
+xtrflags="-fschedule-insns -fschedule-insns2 -fsched-interblock -fstrict-aliasing -fregmove -freorder-blocks"
+xtrflags="$xtrflags -floop-transpose --param max-gcse-passes=3 -malign-natural -ffast-math -faltivec"
+if ${noopt} ; then flags=$nooptflags; flags3=$flags; sflags="-fPIC $flags"
+  else flags3="-mdynamic-no-pic -O3"; flags="$flags3 $xtrflags"; sflags="-fPIC -O3 $xtrflags"
+fi
+if ! ${dyn} ; then sflags=$flags; fi
+##
 
-### Trying slowly to get control over installation paths ...
-# Starting to get rid of hard-coded /usr/local...
-perl -pi.bak -e 's,/usr/local/bin/,,g; s,\$HOME/bin/\$MP_ARCH,/sw/bin,' MP/mpviewer/displaymp
+
+# allow building with external NTL
+sed -ri.bak 's;AC_ARG_WITH\(MP;AC_ARG_ENABLE(NTL, \\\ \n \[    NTL                  NTL\]\)\nAC_ARG_WITH\(MP;g' configure.in
+sed -ri 's;([\]) $;\1;' configure.in
+if ${sntl} ; then
+	## setup2 missing in ntl/Makefile
+	perl -pi.bak -e 's/setup1 setup1/setup1 setup2/g' ntl/Makefile
+	# change GMP_PREFIX in ntl/configure
+	perl -pi.bak -e 's, GMP_PREFIX=\$prefix/\$\{ac_cv_singuname\},,g' ntl/configure
+	# re-run ranlib after cp
+	perl -pi.bak -e 's,cp ntl\.a \$\(LIBDIR\)/libntl\.a,cp ntl\.a \$\(LIBDIR\)/libntl\.a; ranlib \$\(LIBDIR\)/libntl\.a,g' \
+	ntl/src/make.tail
+	### libm is libSystem, and is always searched _ but should be searched last :
+	#perl -pi.bak -e 's/configure/configure NTL_STD_CXX=on LDLIBS=""/g' ntl/configure
+	perl -pi -e 's/configure/configure LDLIBS=""/g' ntl/configure
+	sed -i.bak -e '1i\
+#include <iostream\.h>' ntl/src/{*Test,subset}.c
+	perl -pi.bak -e "s/=\-O2/=$flags3 $mflags $warnflags/g" ntl/src/make.config
+  else
+	rm -fR ntl
+fi
+#
+
+### Getting control over installation paths ...
+# In feResource.cc (note: apparently missing commas are added in second "-e" line, and in second expresion with S_UNAME) :
+sed -ri.bak \
+-e '\,\%d/LIB;,d' -e 's,^((\s|\t)+)\"\$SINGULARPATH;\"\s*$,&\n\1\"\%r/share/singular/LIB;\"\n\1\"\%d/LIB;\",' \
+-e 's/LIB\"$/LIB\",/' \
+-e 's,d/\"S_UNAME\",b,' -e 's|d/\"S_UNAME|r/bin\",|' -e 's,r/doc/singular\.idx,d/singular\.idx,' \
+-e "s,/html,/share/doc/${n}/html," -e 's,/info/singular\.hlp,/share/info/singular\.info,' \
+-e "s,/examples,/share/doc/${n}/examples," -e 's,/netscape,/mozilla,' -e 's,\%b/xterm,/usr/X11R6/bin/xterm,' \
+-e 's,\"\%b;\$PATH\",\"\$PATH\",' -e 's,\"\%r/emacs\",\"\%r/share/singular/emacs\",g' -e "s,\%b/\.\.,${p}," \
+-e 's|SINGULAR_DEFAULT_DIR,|\"\%r/share/singular\",|' Singular/feResource.cc
+# let us also try to install the .so files in /sw/lib/singular (FS policy...)
+#if ${dyn}; then sed -ri -e 's,^((\s|\t)+)\"\%d/LIB;\",\1\"\%r/lib/singular;\"\n&,' Singular/feResource.cc ; fi
+# The above didn't work, Singular really seems to look for them only in its own directory..
+# let us still try to set bindir to /sw/lib/singular
+#if ${dyn}; then sed -ri -e 's,r/bin,r/lib/singular,' -e 's,\%b/,\%r/bin/,g' Singular/feResource.cc ; fi
+## Didn't work either _ even, 'Singular -v' shows 'BinDir : /sw/bin' .... 
+# Removing hard-coded /usr/local...
+perl -pi.bak -e "s,/usr/local/bin/,,g; s,\$HOME/bin/\$MP_ARCH,${p}/bin," MP/mpviewer/displaymp
 perl -pi.bak -e 's,/usr/local,\${prefix}/share/singular/localdir,' {,doc/}Makefile.in
 ### Don't hardcode path, use relative path :
-perl -pi.bak -e 's,\${LN_S} \${SINGULAR},\${LN_S} Singular\-\${SINGULAR_VERSION},' Singular/Makefile.in
+perl -pi -e 's,\${LN_S} \${SINGULAR},\${LN_S} Singular\-\${SINGULAR_VERSION},' Singular/Makefile.in
 ### LIB must be copied to install-dir _ build-dir will disappear
 perl -pi -e 's,\${LN_S} `pwd`/,cp -pR ,' Singular/Makefile.in
 # Same in doc, for html and examples :
@@ -24,7 +87,7 @@ perl -pi -e 's,ln -s `pwd`/,cp -pR ,' doc/Makefile.in
 ###               CPPFLAGS="-I. ${CPPFLAGS}"
 ### EOF
 perl -pi.bak -e 's/AC_TRY_CPP\( #include "values\.h" ,//g; s/CPPFLAGS="\-I\. \${CPPFLAGS}",//g; s/echo "\*\*\* no values\.h";exit\)//g' MP/configure.in
-# And to make values.h found (eg in gcc -no-cpp-precomp -fPIC -I. -I%p/src/singular-2.04-1/ppcMac-darwin/include -DHAVE_CONFIG_H -c MP_Env.c _ in MP/MP)
+# And to make values.h found (eg in gcc -fPIC -I. -I%p/src/singular-2.04-1/ppcMac-darwin/include -DHAVE_CONFIG_H -c MP_Env.c _ in MP/MP)
 ln -s ../values.h MP/MP
 # it is MP_Memory.c
 perl -pi.bak -e 's/ Memory\.c/ MP_Memory\.c/g' MP/MP/Makefile.in
@@ -35,15 +98,9 @@ perl -pi.bak -e 's/ \${OM_MALLOC_HEADER}//g' omalloc/Makefile.in
 ## "--with-malloc=system" breaks down in MP, since there it is "--with-malloc=HEADER"
 ## Thus patch the configure script to ignore the '--with-malloc=system, since the header we need is the default stdlib.h :
 perl -pi -e 's/"\${with_malloc\+set}" = set/0 = 1/g' MP/configure.in
-# setup2 missing in ntl/Makefile
-perl -pi -e 's/setup1 setup1/setup1 setup2/g' ntl/Makefile
-# GMP_PREFIX incorrectly set in ntl/configure
-perl -pi.bak -e 's, GMP_PREFIX=\$prefix/\$\{ac_cv_singuname\},,g' ntl/configure
-# re-run ranlib after cp
-perl -pi.bak -e 's,cp ntl\.a \$\(LIBDIR\)/libntl\.a,cp ntl\.a \$\(LIBDIR\)/libntl\.a; ranlib \$\(LIBDIR\)/libntl\.a,g' ntl/src/make.tail
-# cerr etc undefined in QuickTest.c etc...
+## cerr etc undefined in QuickTest.c etc...
 sed -i.bak -e '1i\
-#include <iostream\.h>' ntl/src/{*Test,subset}.c libfac/test*
+#include <iostream\.h>' libfac/test*
 ## The var $ac_cv_with_readline appears nowhere else in the build tree _ only at 1 place in configure(.in)
 # Everywhere else it is 'with_readline' : seems fixed in 2.05
 #perl -pi.bak -e 's/ac_cv_with_readline/with_readline/g' Singular/configure.in
@@ -54,7 +111,14 @@ sed -i.bak -e '1i\
 # perl -pi.bak -e 's/\(IsCmd\(plib, \&token\)\)/\(IsCmd\(plib, token\)\)/g' Singular/iplib.cc
 ### new problem in 2.05 : HAVE_NAMESPACES leads to error (cf info file)
 perl -pi.bak -e 's,#   define HAVE_NAMESPACES 1,/\* #   define HAVE_NAMESPACES 1 \*/,g' Singular/mod2.h.in
-###
+### w/o the next one, system("sh",whatever) always returns -1 instead of 0
+### (with perror inserted at the following place showing 'No child processes') :
+sed -ri.bak '/strcmp\(sys_cmd,\"sh\"\)/,+13 {
+s/MWERKS__/MWERKS__\n signal\(SIGCHLD, \(void \(\*\)\(int\)\)SIG_DFL\);/
+s/\#endif/signal\(SIGCHLD, \(void \(\*\)\(int\)\)SIG_IGN\);\n \#endif/
+}' Singular/extra.cc
+### The space in -I . seems to work, but I feel more comfortable w/o it ...
+perl -pi.bak -e 's,\-I \.,\-I\.,g' IntegerProgramming/Makefile.in
 ### @ifclear needs a name _ guess is hopefully correct...
 perl -pi.bak -e 's,^\@ifclear$,\@ifclear singularmanual,' doc/INSTALL_win.texi
 ## There is no ../GPL
@@ -64,70 +128,107 @@ perl -pi.bak -e 's,/doc,/info,g' emacs/Makefile.in
 ### and Singular/Makefile is not under $prefix
 perl -pi -e 's,\$\{prefix\}/Singular/Makefile,\.\./Singular/Makefile,g' emacs/Makefile.in
 ### emacs/lib.pl expects to find libparse and LIB in "{prefix}/Singular" while they were installed
-### in ${bindir} and in ${prefix} resp ... The default in lib.pl is OK (except possibly for standalone build of emacs)
+### in ${bindir} and in ${prefix} resp ... The default in lib.pl is OK (except possibly for standalone build of the emacs-dir)
 perl -pi -e 's,\-s \$\{singulardir\} ,,'  emacs/Makefile.in
-### libm is libSystem, and is always searched _ but should be searched last :
-#perl -pi.bak -e 's/configure/configure NTL_STD_CXX=on LDLIBS=""/g' ntl/configure
-perl -pi -e 's/configure/configure LDLIBS=""/g' ntl/configure
+## We put the .el files in %p/share/emacs/site-lisp (and xemacs/site-lisp):
+perl -pi.bak -e 's,\-file \(.*\"\)\)$, "singular"\),g' emacs/.emacs-singular
+###
+
+### libm is libSystem, and is always searched _ but should appear last in the search list if at all:
 perl -pi -e 's/\-lm //g' Singular/Makefile.in
+perl -pi.bak -e 's/AC_CHECK_LIB\(m, atof\)/if test \"\$ac_cv_singuname\" \!= ppcMac-darwin; then\nAC_CHECK_LIB\(m, atof\)\nfi/g' Singular/configure.in
 ###
 
 ### Getting readline to be used (trying to _ don't understand this mess they did with readline...) :
-perl -pi.bak -e 's/"\$with_readline" != dynamic && test //g' Singular/configure.in
+perl -pi -e 's/"\$with_readline" != dynamic && test //g' Singular/configure.in
 ###
 
-### changing .so suffixes to dylib ... (FIXME: probably better to use bundle and bundle-loader)
+### changing some .so suffixes to dylib ...
 perl -pi.bak -e 's/\"libreadline\.so\"\);/\"libreadline\.dylib\"\);\n\tif (fe_rl_hdl==NULL) fe_rl_hdl=dynl_open("libreadline.so");/g' Singular/fereadl.c
 perl -pi.bak -e 's/{ "",/{ "", "\.dylib",/g' Singular/iplib.cc
-perl -pi -e 's/\.so(=|:|\n|\))/\.dylib\1/g; s/\*\.so\*/\*\.so\* \*\.dylib\*/g' Singular/Makefile.in
-perl -pi.bak -e 's/"so"/"dylib"/g' Singular/mod_raw.cc
 ###
 
 ### dynamic loading
 # how to do dynamic loading (1)
 perl -pi -e 's,#if defined\(ix86_Linux\),#if defined\(ppcMac_darwin\)\n#define HAVE_ELF_SYSTEM\n#endif\n\n#if defined\(ix86_Linux\),g' Singular/mod_raw.cc
 # how to do dynamic loading (2)
-### The '-single_module' below is to avoid :
-### ld: common symbols not allowed with MH_DYLIB output format with the -multi_module option
-### fereadl.o definition of common _fe_rl_outstream (size 4)
-### (many such)
 ## Have to try if there is a way to use continuation lines in commands like the following ... 
-# (Temporarily ?) rm'd ' -dynamiclib -single_module \-undefined dynamic_lookup' from the LD_DYN_FLAGS
-perl -pi -e 's|ac_cv_singuname\" in|ac_cv_singuname\" in\n\tppcMac\-darwin\)\n\t  AC_CHECK_LIB\(dl, dlopen\)\n\t  if test \"\$ac_cv_lib_dl_dlopen\" = yes; then\n\t\tLD_DYN_FLAGS=\"\-ldl\"\n\t\tSFLAGS=\"\-DPIC\"\n\t\tSLDFLAGS=\"\-dynamiclib \-undefined dynamic_lookup\"\n\t\tLD=g\+\+\n\t\tac_lib_dl=yes\n\t  fi\n\t;;|g' Singular/configure.in
+perl -pi -e "s|ac_cv_singuname\" in|ac_cv_singuname\" in\n\tppcMac\-darwin\)\n\t  AC_CHECK_LIB\(dl, dlopen\)\n\t  if test \"TST\" = yes; then\n\t\tLD_DYN_FLAGS=\"\"\n\t\tSFLAGS=\"\-DPIC $sflags\"\n\t\tSLDFLAGS=\"\-bundle \-bundle_loader Singular\"\n\t\tLD=g\+\+\n\t\tac_lib_dl=yes\n\t  fi\n\t;;|g" Singular/configure.in
+perl -pi -e 's|TST|\$ac_cv_lib_dl_dlopen|g' Singular/configure.in
+# re-link the modules (*.so) with -bundle_loader in the presence of Singular (else execution-time error in doc/examples/watchdog:
+## > malloc[27548]: Deallocation of a pointer not malloced: 0x304154; This could be a double free(), or free() called
+## > with the middle of an allocated block; Try setting environment variable MallocHelp to see tools to help debug
+# ). Just changing the build-order suffices (by laziness we put the dep on Singular in the .dl_o targets rather than the
+# .so targets, since it seems inconvenient to dipense with "$^" in mpsr.so and dbmsr.so) :
+### # (note that $DL_LIBS is empty when doing a static build)
+perl -pi -e 's, \$\(DL_LIBS\)$,,' Singular/Makefile.in
+perl -pi -e 's,SING_EXEC\),$& \$\(DL_LIBS\),,' Singular/Makefile.in
+#sed -ri -e '/\.so:/s/$/ \$\(SING_EXEC\)/' Singular/Makefile.in
+# To fully link mpsr.so we need to add -lgmp at the end of the MP_LIBS :
+sed -ri -e 's,^dnl MP_LIBS=\$\{LIBS\}$,MP_LIBS=\"\-lgmp\",' Singular/configure.in
+# and same problem with p_Procs_FieldQ.so (needs __gmpz_init_set )
+# (we could just add -lgmp for all, but then otool -L would show fake deps for the other p_Procs_Field*.so) :
+sed -ri \
+-e '/\%\.dl_o \:/s/$/ \$\(SING_EXEC\)/' -e '/^p_Procs_\%\.so\:/,+1s/\^/\</' \
+-e 's/^p_Procs_\%\.so\:/p_Procs_FieldQ\.so\: p_Procs_Lib_FieldQ\.dl_o\n\t\$\(LD\) \$\{SLDFLAGS\} \-o \$\@ \$\< \-lgmp\n\n&/' \
+Singular/Makefile.in
+
+
 # remove temporarily -w flags
-# Also add the -dynamic -fno-common flags in Singular
-perl -pi.bak -e 's/\-O2/-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' omalloc/configure
-#perl -pi -e 's/\-O(3|)/$& -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' omalloc/Makefile.in
-perl -pi -e 's/\-O(3|)/-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' omalloc/Makefile.in
-perl -pi.bak -e 's/=\-O2/=\-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' ntl/src/def_makefile
-perl -pi.bak -e 's/=\-O2/=\-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' ntl/src/make.config 
-perl -pi -e 's/\-O3 \-w/-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' MP/configure.in
-perl -pi.bak -e 's/\-w$/ -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' factory/GNUmakefile.in
-perl -pi.bak -e 's/\-O2/-O0/g' factory/configure.in
-perl -pi.bak -e 's/\-O3/-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' libfac/configure.in
-perl -pi -e 's/\-O3 \-w /\-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp /g' Singular/configure.in
-perl -pi -e 's/\"\-w\"/\"\-Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp\"/g' Singular/configure.in
-perl -pi -e 's/\-O2 \-w/-O0 -Wall -Wcast-align -W -Wshadow -Wno-unused -no-cpp-precomp/g' Singular/Makefile.in
-# get the patch into the configure scripts
-cd MP ; autoconf ; cd ..
-cd factory ; autoconf ; cd ..
-cd libfac ; autoconf ; cd ..
-cd Singular ; autoconf ; cd ..
+## Also add -fno-common flags, just to be safe
+###
+# Apparently we need to use -fPIC in MPT, else linking trouble in Singular :
+# > g++ -dynamiclib -undefined dynamic_lookup -o mpsr.dylib mpsr_Put.dl_o mpsr_PutPoly.dl_o mpsr_GetPoly.dl_o mpsr_sl.dl_o
+# > mpsr_Get.dl_o mpsr_GetMisc.dl_o mpsr_Error.dl_o -L/sw/src/root-singular-dyn-2.05-4/sw/lib -lMPT -lMP
+# > ld: /sw/src/root-singular-dyn-2.05-4/sw/lib/libMPT.a(MPT_Get.o) has local relocation entries in non-writable section (__TEXT,
+# > /usr/bin/libtool: internal link edit command failed
+# And -fno-common in MP/MP; else :
+# > g++ -dynamiclib -undefined dynamic_lookup -o mpsr.dylib mpsr_Put.dl_o mpsr_PutPoly.dl_o mpsr_GetPoly.dl_o mpsr_sl.dl_o
+# > mpsr_Get.dl_o mpsr_GetMisc.dl_o mpsr_Error.dl_o -L/sw/src/root-singular-dyn-2.05-4/sw/lib -lMPT -lMP
+# > ld: common symbols not allowed with MH_DYLIB output format with the -multi_module option
+# > /sw/src/root-singular-dyn-2.05-4/sw/lib/libMP.a(MP_Util.o) definition of common _fix_log_msg (size 128)
+# > /sw/src/root-singular-dyn-2.05-4/sw/lib/libMP.a(MP_Util.o) definition of common _AnnotFlagsStr (size 32)
+# > /usr/bin/libtool: internal link edit command failed
+### For the moment, rather than adding -fno-common in MP/MP, let us try to make bundles rather than dylibs.. _ WORKS !
+#
+# We take the opportunity at the same time to get here a separate handle on the CFLAGS in each dir
+# Also, we set optimization to 0 for the moment _ will try gradually to increase them to (at least) their defaults,
+# to see separately which errors each increase causes, and fix them before the next increase..
+# In omalloc, we get rid at the same time of the '-g' flags, in order to be able to grep for %p/src in binary files
+# w/o false alarms.
+# The first line just gives a handle, with the default level of -O2 otherwise generated by autoconf
+sed -ri.bak -e '/CFLAGS\+set/,+3s/^dnl //' -e 's/"\-O"/"-O2"/' omalloc/configure.in
+perl -pi -e "s/\-O2/$flags $mflags $warnflags/g" omalloc/configure.in
+perl -pi -e "s/\-O(3|)/$flags $mflags $warnflags/g" omalloc/Makefile.in
+# We need -fPIC, hence $sflags, in MP (maybe just in MP/MP ??
+#  msg was ".../libMP.a(MP_Put.o) has local relocation entries in non-writable section (__TEXT,__text)")
+perl -pi -e "s/\-O3 \-w/$sflags $mflags $warnflags/g" MP/configure.in
+perl -pi.bak -e "s/\t\-w/\t $warnflags/g" factory/GNUmakefile.in
+perl -pi.bak -e "s/\-O2/$flags $mflags/g" factory/configure.in
+perl -pi.bak -e "s/\-O3/$flags $mflags $warnflags/g" libfac/configure.in
+sed -ri -e 's/CFLAGS=\"\-O3 \-w/CFLAGS=\"\-fast/' -e "s/\-fast/$flags $mflags $warnflags/" Singular/configure.in
+perl -pi -e "s/\-O3 \-w /$flags $mflags $warnflags /g" Singular/configure.in
+#perl -pi -e "s/\"\-w\"/\"$warnflags\"/g" Singular/configure.in
+# Next plays no role
+#perl -pi -e "s/\-O2 \-w/-O2 $mflags $warnflags/g" Singular/Makefile.in
+sed -ri -e "s/\-O2 *([$])/$flags $mflags $warnflags \1/g" Singular/Makefile.in
+# -fast causes runtime errors, thus -O3:
+perl -pi -e "s/\@CXXFLAGS\@/$flags3 $mflags $warnflags/g" IntegerProgramming/Makefile.in
 ####
 
-#### C-C++ linking
-## The declaration 'extern int dynl_close ...' in Singular/ipid.cc:896 needs rather 'extern "C"' (for correct linking)
-## However just adding the "C" leads to a 'ipid.cc:896: error: parse error before string constant'
-## Apparently the extern "C" declaration has to come outside the scope, not only of the "if block" containing it
-## (logical _ what means a declaration that is conditional on execution-time circumstances), but even of the
-## whole function ( paCleanUp ) containing it... (have still to understand why).
-## Thus we rather include the corresponding header mod_raw.h, which contains its own extern "C" with #ifdef cplusplus wrappers
-## (has also to be included at the top level _ same reason.
-######### Fixed in vers 2.05
-# perl -pi.bak -e 's,^#include "ipid.h",#include "ipid.h"\n#include "mod_raw.h",g; s,^ *extern int dynl_close \(void \*handle\);,,g' Singular/ipid.cc
-## gmp.h can _ and must _ be included w/o any 'extern "C"' or '#undef __cplusplus'
-perl -pi.bak -e 's/(extern "C" {\n|}\n|.*cplusplus.*\n|#else\n|#endif\n)//g; s/#include <gmp\.h>\n/#include <gmp.h>/g' factory/cf_gmp.h
-perl -pi -e 's/>#include <gmp\.h>/>/g' factory/cf_gmp.h
+## Add flags that should be in -O2 and are probably not in -Os :
+xtrflags="$xtrflags -falign-functions -falign-jumps -falign-loops -falign-labels -fprefetch-loop-arrays"
+# now get to -O3 (and add -Os -mdynamic-no-pic etc):
+xtrflags="-Os -mdynamic-no-pic $xtrflags -finline-functions -frename-registers $mflags $warnflags -fomit-frame-pointer"
+sed -ri -e \
+"s/^version\.h:/hdegree.o: hdegree.cc\n\t\$\{CXX\} $xtrflags \$\{CXXTEMPLFLAGS\} \$\{CPPFLAGS\} \$\{DEFS\} \-c \$\<\n\n&/" \
+Singular/Makefile.in
+
+# To enable the streamio switch :
+if ${strio} ; then
+  perl -pi -e "s,streamio=no,streamio=yes," factory/configure.in
+  sed -ri -e '/AC_DEFINE\(SINGULAR\)/,+1{/AC_DEFINE\(NOSTREAMIO\)/d}' libfac/configure.in
+fi
 
 ## For safety, after all those changes make sure to run 'make depend'
 perl -pi -e 's,stamp\-h$,stamp\-h depend,g' omalloc/Makefile.in
@@ -135,4 +236,11 @@ perl -pi -e 's,Config\.h\.in$,Config\.h\.in depend,g' MP/MP/Makefile.in
 perl -pi.bak -e 's,^install:,install: depend,g' MP/MPT/Makefile.in
 perl -pi -e 's,stamp\-h$,stamp\-h depend,g' Singular/Makefile.in
 
-# Why does test mpsr_s ask for my (root-)password (Building as root) ???
+
+## Putting the changes into the configure scripts
+cd omalloc; autoconf; cd ..
+cd MP ; autoconf ; cd ..
+cd factory ; autoconf ; cd ..
+cd libfac ; autoconf ; cd ..
+cd Singular ; autoconf ; cd ..
+autoconf
