moved kinstalltheme call to the kde startup

diff --git a/crypto/rangerrick/finkinfo/kdebase3-ssl-3.1.2-1.patch b/crypto/rangerrick/finkinfo/kdebase3-ssl-3.1.2-1.patch
--- a/crypto/rangerrick/finkinfo/kdebase3-ssl-3.1.2-1.patch
+++ b/crypto/rangerrick/finkinfo/kdebase3-ssl-3.1.2-1.patch
@@ -1,6 +1,6 @@
 
 --- startkde	6 May 2003 17:48:14 -0000	1.1.1.8
-+++ startkde	6 May 2003 18:23:14 -0000	1.12
++++ startkde	14 May 2003 13:43:52 -0000	1.13
 @@ -34,6 +34,10 @@
  # people's heads. We use colours from the standard KDE palette for those with
  # palettised displays.
@@ -45,6 +45,17 @@
  ksplash
  
  # We set LD_BIND_NOW to increase the efficiency of kdeinit.
+@@ -150,6 +162,10 @@
+   echo 'startkde: Could not start kdeinit. Check your installation.'  1>&2
+   xmessage -geometry 500x100 "Could not start kdeinit. Check your installation."
+ fi
++
++# fix up KDE themes
++echo 'startkde: updating theme cache'
++kwrapper kinstalltheme
+ 
+ # finally, give the session control to the session manager
+ # if the KDEWM environment variable has been set, then it will be used as KDE's
 RCS file: debian/konsole.links
 diff -N debian/konsole.links
 RCS file: doc/kaddressbook/index.cache.bz2
