new i18n, buncha un-built updates

diff --git a/rangerrick/10.2-gcc3.3/crypto/finkinfo/kdebase3-ssl.patch b/rangerrick/10.2-gcc3.3/crypto/finkinfo/kdebase3-ssl.patch
--- a/rangerrick/10.2-gcc3.3/crypto/finkinfo/kdebase3-ssl.patch
+++ b/rangerrick/10.2-gcc3.3/crypto/finkinfo/kdebase3-ssl.patch
@@ -1,6 +1,127 @@
-diff -uNr kdebase-3.2.92/kdeprint/kprinter/printwrapper.cpp kdebase-3.2.92-new/kdeprint/kprinter/printwrapper.cpp
---- kdebase-3.2.92/kdeprint/kprinter/printwrapper.cpp	2004-05-22 16:26:46.000000000 -0400
-+++ kdebase-3.2.92-new/kdeprint/kprinter/printwrapper.cpp	2004-07-25 12:32:00.000000000 -0400
+--- kdebase-3.3.0/configure	Mon Aug 16 05:24:19 2004
++++ kdebase-3.3.0-new/configure	Sun Aug 22 16:36:47 2004
+@@ -9636,10 +9636,21 @@
+       archive_cmds_need_lc=no
+       case "$host_os" in
+       rhapsody* | darwin1.[012])
+-	allow_undefined_flag='-undefined suppress'
++	allow_undefined_flag='-Wl,-undefined -Wl,suppress'
+ 	;;
+       *) # Darwin 1.3 on
+-	test -z ${LD_TWOLEVEL_NAMESPACE} && allow_undefined_flag='-flat_namespace -undefined suppress'
++	if test -z ${MACOSX_DEPLOYMENT_TARGET} ; then
++	  allow_undefined_flag='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	else
++	  case ${MACOSX_DEPLOYMENT_TARGET} in
++	    10.[012])
++	      allow_undefined_flag='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	      ;;
++	    10.*)
++	      allow_undefined_flag='-Wl,-undefined -Wl,dynamic_lookup'
++	      ;;
++	  esac
++	fi
+ 	;;
+       esac
+     	lt_int_apple_cc_single_mod=no
+@@ -11486,10 +11497,21 @@
+     archive_cmds_need_lc=no
+     case "$host_os" in
+     rhapsody* | darwin1.[012])
+-      allow_undefined_flag='-undefined suppress'
++      allow_undefined_flag='-Wl,-undefined -Wl,suppress'
+       ;;
+     *) # Darwin 1.3 on
+-      test -z ${LD_TWOLEVEL_NAMESPACE} && allow_undefined_flag='-flat_namespace -undefined suppress'
++	if test -z ${MACOSX_DEPLOYMENT_TARGET} ; then
++	  allow_undefined_flag='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	else
++	  case ${MACOSX_DEPLOYMENT_TARGET} in
++	    10.[012])
++	      allow_undefined_flag='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	      ;;
++	    10.*)
++	      allow_undefined_flag='-Wl,-undefined -Wl,dynamic_lookup'
++	      ;;
++	  esac
++	fi
+       ;;
+     esac
+     output_verbose_link_cmd='echo'
+@@ -12537,10 +12559,21 @@
+     archive_cmds_need_lc_CXX=no
+     case "$host_os" in
+     rhapsody* | darwin1.[012])
+-      allow_undefined_flag_CXX='-undefined suppress'
++      allow_undefined_flag_CXX='-Wl,-undefined -Wl,suppress'
+       ;;
+     *) # Darwin 1.3 on
+-      test -z ${LD_TWOLEVEL_NAMESPACE} && allow_undefined_flag_CXX='-flat_namespace -undefined suppress'
++	if test -z ${MACOSX_DEPLOYMENT_TARGET} ; then
++	  allow_undefined_flag_CXX='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	else
++	  case ${MACOSX_DEPLOYMENT_TARGET} in
++	    10.[012])
++	      allow_undefined_flag_CXX='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	      ;;
++	    10.*)
++	      allow_undefined_flag_CXX='-Wl,-undefined -Wl,dynamic_lookup'
++	      ;;
++	  esac
++	fi
+       ;;
+     esac
+     lt_int_apple_cc_single_mod=no
+@@ -16360,10 +16393,21 @@
+       archive_cmds_need_lc_F77=no
+       case "$host_os" in
+       rhapsody* | darwin1.[012])
+-	allow_undefined_flag_F77='-undefined suppress'
++	allow_undefined_flag_F77='-Wl,-undefined -Wl,suppress'
+ 	;;
+       *) # Darwin 1.3 on
+-	test -z ${LD_TWOLEVEL_NAMESPACE} && allow_undefined_flag_F77='-flat_namespace -undefined suppress'
++	if test -z ${MACOSX_DEPLOYMENT_TARGET} ; then
++	  allow_undefined_flag_F77='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	else
++	  case ${MACOSX_DEPLOYMENT_TARGET} in
++	    10.[012])
++	      allow_undefined_flag_F77='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	      ;;
++	    10.*)
++	      allow_undefined_flag_F77='-Wl,-undefined -Wl,dynamic_lookup'
++	      ;;
++	  esac
++	fi
+ 	;;
+       esac
+     	lt_int_apple_cc_single_mod=no
+@@ -18642,10 +18686,21 @@
+       archive_cmds_need_lc_GCJ=no
+       case "$host_os" in
+       rhapsody* | darwin1.[012])
+-	allow_undefined_flag_GCJ='-undefined suppress'
++	allow_undefined_flag_GCJ='-Wl,-undefined -Wl,suppress'
+ 	;;
+       *) # Darwin 1.3 on
+-	test -z ${LD_TWOLEVEL_NAMESPACE} && allow_undefined_flag_GCJ='-flat_namespace -undefined suppress'
++	if test -z ${MACOSX_DEPLOYMENT_TARGET} ; then
++	  allow_undefined_flag_GCJ='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	else
++	  case ${MACOSX_DEPLOYMENT_TARGET} in
++	    10.[012])
++	      allow_undefined_flag_GCJ='-Wl,-flat_namespace -Wl,-undefined -Wl,suppress'
++	      ;;
++	    10.*)
++	      allow_undefined_flag_GCJ='-Wl,-undefined -Wl,dynamic_lookup'
++	      ;;
++	  esac
++	fi
+ 	;;
+       esac
+     	lt_int_apple_cc_single_mod=no
+--- kdebase-3.3.0/kdeprint/kprinter/printwrapper.cpp	Sat May 22 16:26:46 2004
++++ kdebase-3.3.0-new/kdeprint/kprinter/printwrapper.cpp	Sat Aug 21 20:22:43 2004
 @@ -137,10 +137,6 @@
  {
  	KCmdLineArgs	*args = KCmdLineArgs::parsedArgs();
@@ -12,20 +133,39 @@ diff -uNr kdebase-3.2.92/kdeprint/kprinter/printwrapper.cpp kdebase-3.2.92-new/k
  	// read variables from command line
  	QString	printer = args->getOption("d");
  	QString	title = args->getOption("t");
-@@ -321,6 +317,10 @@
+@@ -320,6 +316,10 @@
+ 	if (filestoprint.count() == 0)
  	{
  		// print from stdin
- 
-+#if defined(HAVE_SIGACTION) && !defined(HAVE_SIGSET)
-+		struct sigaction action;
-+#endif /* HAVE_SIGACTION && !HAVE_SIGSET*/
 +
++#if defined(HAVE_SIGACTION) && !defined(HAVE_SIGSET)
++	struct sigaction action;
++#endif /* HAVE_SIGACTION && !HAVE_SIGSET*/
+ 
  #  if defined(HAVE_SIGSET)
  		sigset(SIGHUP, signal_handler);
- 		sigset(SIGINT, signal_handler);
-diff -uNr kdebase-3.2.92/kioslave/info/kde-info2html.conf kdebase-3.2.92-new/kioslave/info/kde-info2html.conf
---- kdebase-3.2.92/kioslave/info/kde-info2html.conf	2004-05-22 16:26:52.000000000 -0400
-+++ kdebase-3.2.92-new/kioslave/info/kde-info2html.conf	2004-07-25 12:31:20.000000000 -0400
+--- kdebase-3.3.0/kioslave/Makefile.in	Mon Aug 16 05:23:45 2004
++++ kdebase-3.3.0-new/kioslave/Makefile.in	Sat Aug 21 20:21:41 2004
+@@ -64,7 +64,7 @@
+ 	uninstall-recursive nmcheck-recursive bcheck-recursive
+ ETAGS = etags
+ CTAGS = ctags
+-DIST_SUBDIRS = about cgi floppy filter fish info mac man nfs nntp pop3 \
++DIST_SUBDIRS = about cgi floppy filter fish info mac man nntp pop3 \
+ 	imap4 smtp sftp tar finger thumbnail ldap smb devices settings
+ #>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
+ #>+ 1
+@@ -496,7 +496,7 @@
+ @include_kioslave_ldap_TRUE@LDAP_SUBDIR = ldap
+ @include_kioslave_smb_TRUE@SMB_SUBDIR = smb
+ @include_devicesdir_TRUE@DEVICES_SUBDIR = devices
+-SUBDIRS = about cgi floppy filter fish info mac man nfs nntp pop3 imap4 smtp \
++SUBDIRS = about cgi floppy filter fish info mac man nntp pop3 imap4 smtp \
+   sftp tar finger thumbnail $(LDAP_SUBDIR) $(SMB_SUBDIR) $(DEVICES_SUBDIR) settings
+ 
+ #>- all: all-recursive
+--- kdebase-3.3.0/kioslave/info/kde-info2html.conf	Sat May 22 16:26:52 2004
++++ kdebase-3.3.0-new/kioslave/info/kde-info2html.conf	Sat Aug 21 20:23:06 2004
 @@ -25,6 +25,7 @@
  
  #-- location of info files.
@@ -34,9 +174,8 @@ diff -uNr kdebase-3.2.92/kioslave/info/kde-info2html.conf kdebase-3.2.92-new/kio
  	    "/usr/share/info",
  	    "/usr/info",
  	    "/usr/lib/info",
-diff -uNr kdebase-3.2.92/kioslave/man/kio_man.cpp kdebase-3.2.92-new/kioslave/man/kio_man.cpp
---- kdebase-3.2.92/kioslave/man/kio_man.cpp	2004-06-22 13:32:52.000000000 -0400
-+++ kdebase-3.2.92-new/kioslave/man/kio_man.cpp	2004-07-25 12:31:20.000000000 -0400
+--- kdebase-3.3.0/kioslave/man/kio_man.cpp	Thu Aug  5 14:57:13 2004
++++ kdebase-3.3.0-new/kioslave/man/kio_man.cpp	Sat Aug 21 20:24:08 2004
 @@ -50,7 +50,7 @@
  
  MANProtocol *MANProtocol::_self = 0;
@@ -46,43 +185,48 @@ diff -uNr kdebase-3.2.92/kioslave/man/kio_man.cpp kdebase-3.2.92-new/kioslave/ma
  
  /*
   * Drop trailing ".section[.gz]" from name
-diff -uNr kdebase-3.2.92/libkonq/Makefile.am kdebase-3.2.92-new/libkonq/Makefile.am
---- kdebase-3.2.92/libkonq/Makefile.am	2004-05-22 16:27:06.000000000 -0400
-+++ kdebase-3.2.92-new/libkonq/Makefile.am	2004-07-25 12:31:20.000000000 -0400
-@@ -21,7 +21,7 @@
+@@ -862,6 +862,7 @@
+                         "/usr/sunpc/man",
+                         "/usr/ncd/man",
+                         "/usr/newsprint/man",
++                        "@PREFIX@/share/man",
+                         NULL };
  
- lib_LTLIBRARIES = libkonq.la
- libkonq_la_LDFLAGS = $(all_libraries) -version-info 6:0:2 -no-undefined
+ 
+--- kdebase-3.3.0/ksysguard/ksysguardd/ksysguardd.c	Sat Jul 17 13:52:09 2004
++++ kdebase-3.3.0-new/ksysguard/ksysguardd/ksysguardd.c	Sun Aug 22 12:22:09 2004
+@@ -433,7 +433,7 @@
+     if ( FD_ISSET( socketNo, fds ) ) {
+       int clientsocket;
+       struct sockaddr addr;
+-      socklen_t addr_len = sizeof( struct sockaddr );
++      kde_socklen_t addr_len = sizeof( struct sockaddr );
+ 
+       /* a new connection */
+       if ( ( clientsocket = accept( socketNo, &addr, &addr_len ) ) < 0 ) {
+--- kdebase-3.3.0/libkonq/Makefile.in	Mon Aug 16 05:24:15 2004
++++ kdebase-3.3.0-new/libkonq/Makefile.in	Sat Aug 21 20:24:37 2004
+@@ -588,7 +588,7 @@
+ #>- libkonq_la_LDFLAGS = $(all_libraries) -version-info 6:0:2 -no-undefined
+ #>+ 1
+ libkonq_la_LDFLAGS = $(all_libraries) -version-info 6:0:2 -no-undefined $(KDE_NO_UNDEFINED)
 -libkonq_la_LIBADD = $(LIB_KPARTS)
 +libkonq_la_LIBADD = $(LIB_KPARTS) $(LIBZ)
- 
- libkonq_la_SOURCES = konq_popupmenu.cc knewmenu.cc \
-    konq_xmlguiclient.cc\
-diff -uNr kdebase-3.2.92/startkde kdebase-3.2.92-new/startkde
---- kdebase-3.2.92/startkde	2004-07-17 13:51:54.000000000 -0400
-+++ kdebase-3.2.92-new/startkde	2004-07-25 12:31:20.000000000 -0400
-@@ -26,6 +26,8 @@
-   esac
- fi
+ #>- libkonq_la_SOURCES = konq_popupmenu.cc knewmenu.cc \
+ #>-    konq_xmlguiclient.cc\
+ #>-    kfileivi.cc konq_iconviewwidget.cc konq_settings.cc konq_drag.cc  \
+--- kdebase-3.3.0/startkde	Thu Aug  5 14:56:53 2004
++++ kdebase-3.3.0-new/startkde	Sat Aug 21 20:27:02 2004
+@@ -3,6 +3,8 @@
+ #  DEFAULT KDE STARTUP SCRIPT ( KDE-3.3 )
+ #
  
 +source "@PREFIX@/bin/init.sh"
 +
- # Boot sequence:
- #
- # kdeinit is used to fork off processes which improves memory usage
-@@ -86,6 +88,11 @@
- # Where X is the original font database that was set up before this script
- # runs.
- 
-+/usr/X11R6/bin/xmodmap -e "keycode 74 = Right"
-+/usr/X11R6/bin/xmodmap -e "keycode 78 = Left"
-+/usr/X11R6/bin/xmodmap -e "keycode 80 = Down"
-+/usr/X11R6/bin/xmodmap -e "keycode 85 = Up"
-+
- usr_odir=$HOME/.fonts/kde-override
- usr_fdir=$HOME/.fonts
- 
-@@ -190,7 +197,7 @@
+ # When the X server dies we get a HUP signal from xinit. We must ignore it
+ # because we still need to do some cleanup.
+ trap 'echo GOT SIGHUP' HUP
+@@ -192,7 +194,7 @@
      done
      dcopserver_shutdown
      # shutdown will also make kwin quit, give it time to do so
@@ -91,7 +235,7 @@ diff -uNr kdebase-3.2.92/startkde kdebase-3.2.92-new/startkde
  fi
  
  # the splashscreen and progress indicator
-@@ -214,7 +221,29 @@
+@@ -216,7 +218,29 @@
  # We only check for 255 which means that the ksmserver process could not be 
  # started, any problems thereafter, e.g. ksmserver failing to initialize, 
  # will remain undetected.
@@ -99,24 +243,24 @@ diff -uNr kdebase-3.2.92/startkde kdebase-3.2.92-new/startkde
 +
 +USE_PROXY=0
 +if test -n "$KDEWM"; then
-+	if test -z `expr "$KDEWM" : '\(.*quartz-wm.*\)'`; then
-+		USE_PROXY=1
-+	fi
-+	KDEWM="--windowmanager $KDEWM"
++  if test -z `expr "$KDEWM" : '\(.*quartz-wm.*\)'`; then
++    USE_PROXY=1
++  fi
++  KDEWM="--windowmanager $KDEWM"
 +else
-+	KDEWM="--windowmanager kwin"
-+	USE_PROXY=1
++  KDEWM="--windowmanager kwin"
++  USE_PROXY=1
 +fi
 +
 +if test "$USE_PROXY" = "1"; then
-+	if test -x /usr/X11R6/bin/quartz-wm; then
-+		/usr/X11R6/bin/quartz-wm --only-proxy >/dev/null 2>&1 &
-+	else
-+		AUTOCUTSEL=`which autocutsel 2>/dev/null`
-+		if test -n "$AUTOCUTSEL" && test -x "$AUTOCUTSEL"; then
-+			$AUTOCUTSEL >/dev/null 2>&1 &
-+		fi
-+	fi
++  if test -x /usr/X11R6/bin/quartz-wm; then
++    /usr/X11R6/bin/quartz-wm --only-proxy >/dev/null 2>&1 &
++  else
++    AUTOCUTSEL=`which autocutsel 2>/dev/null`
++    if test -n "$AUTOCUTSEL" && test -x "$AUTOCUTSEL"; then
++      $AUTOCUTSEL >/dev/null 2>&1 &
++    fi
++  fi
 +fi
 +
  kwrapper ksmserver $KDEWM 
