fixing for 10.2?

diff --git a/rangerrick/common/main/finkinfo/net/opennms.patch b/rangerrick/common/main/finkinfo/net/opennms.patch
--- a/rangerrick/common/main/finkinfo/net/opennms.patch
+++ b/rangerrick/common/main/finkinfo/net/opennms.patch
@@ -89,3 +89,24 @@ diff -uNr opennms-1.1.4-1/source/tools/packages/fink/README.Darwin opennms-1.1.4
 +  sudo @PREFIX@/bin/opennms start
 +  sudo @PREFIX@/bin/tomcat4 start
  
+diff -uNr opennms-1.1.4-1/source/tools/run/runjava opennms-1.1.4-1-new/source/tools/run/runjava
+--- opennms-1.1.4-1/source/tools/run/runjava	Mon Oct 25 14:24:52 2004
++++ opennms-1.1.4-1-new/source/tools/run/runjava	Wed Oct 27 16:51:30 2004
+@@ -94,7 +94,7 @@
+ #
+ javaCheck() {
+     ret="`$JP -version 2>&1 | grep '^java version' | sed 's/^java version \"//;s/\".*//'`"
+-    if echo "$ret" | egrep '^1\.4\.[2-9]' > /dev/null; then
++    if echo "$ret" | egrep '^1\.4\.[1-9]' > /dev/null; then
+ 	return 0
+     else
+ 	return 1
+@@ -246,7 +246,7 @@
+ 
+     if [ $? -ne 0 ]; then
+ 	warn "error: bad version for configured Java runtime environment"
+-	warn "\"$JP -version\" does not report that is version 1.4.2+"
++	warn "\"$JP -version\" does not report that is version 1.4.1+"
+ 	warn "$mantra"
+ 
+ 	return 1
